language: ruby
script: bundle exec rake test:units

before_install:
  - gem install bundler

rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.6
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler
